/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.15.3.0 (NJsonSchema v9.10.27.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import 'rxjs/add/observable/fromPromise';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/operator/catch';

import { Observable } from 'rxjs/Observable';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpResponseBase, HttpErrorResponse } from '@angular/common/http';

import * as moment from 'moment';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class VisionClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    /**
     * POST Annotate Photo using Google Vision API
     * @return Success
     */
    visionAnnotate(visionRequestParams: VisionRequestParams): Observable<VisionResponse> {
        let url_ = this.baseUrl + "/vision/annotate";
        url_ = url_.replace(/[?&]$/, "");

      console.log(url_);

      const content_ = JSON.stringify(visionRequestParams);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).flatMap((response_ : any) => {
            return this.processVisionAnnotate(response_);
        }).catch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processVisionAnnotate(<any>response_);
                } catch (e) {
                    return <Observable<VisionResponse>><any>Observable.throw(e);
                }
            } else
                return <Observable<VisionResponse>><any>Observable.throw(response_);
        });
    }

    protected processVisionAnnotate(response: HttpResponseBase): Observable<VisionResponse> {
      console.error(JSON.stringify(response));
      const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            console.log(status)
            return blobToText(responseBlob).flatMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? VisionResponse.fromJS(resultData200) : new VisionResponse();
            return Observable.of(result200);
            });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).flatMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of<VisionResponse>(<any>null);
    }

    /**
     * GET Get Response by Type
     * @return Success
     */
    getResponse(responseType: string, id: string): Observable<VisionResponse> {
        let url_ = this.baseUrl + "/vision/{id}?";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (responseType === undefined || responseType === null)
            throw new Error("The parameter 'responseType' must be defined and cannot be null.");
        else
            url_ += "responseType=" + encodeURIComponent("" + responseType) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).flatMap((response_ : any) => {
            return this.processGetResponse(response_);
        }).catch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetResponse(<any>response_);
                } catch (e) {
                    return <Observable<VisionResponse>><any>Observable.throw(e);
                }
            } else
                return <Observable<VisionResponse>><any>Observable.throw(response_);
        });
    }

    protected processGetResponse(response: HttpResponseBase): Observable<VisionResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).flatMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? VisionResponse.fromJS(resultData200) : new VisionResponse();
            return Observable.of(result200);
            });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).flatMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Observable.of<VisionResponse>(<any>null);
    }
}

export class VisionRequestParams implements IVisionRequestParams {
    imageContent: string;

    constructor(data?: IVisionRequestParams) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.imageContent = data["imageContent"] !== undefined ? data["imageContent"] : <any>null;
        }
    }

    static fromJS(data: any): VisionRequestParams {
        data = typeof data === 'object' ? data : {};
        let result = new VisionRequestParams();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["imageContent"] = this.imageContent !== undefined ? this.imageContent : <any>null;
        return data;
    }
}

export interface IVisionRequestParams {
    imageContent: string;
}

export class LabelAnnotationsItemType implements ILabelAnnotationsItemType {
    mid: string;
    description: string;
    score: number;
    topicality: number;

    constructor(data?: ILabelAnnotationsItemType) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.mid = data["mid"] !== undefined ? data["mid"] : <any>null;
            this.description = data["description"] !== undefined ? data["description"] : <any>null;
            this.score = data["score"] !== undefined ? data["score"] : <any>null;
            this.topicality = data["topicality"] !== undefined ? data["topicality"] : <any>null;
        }
    }

    static fromJS(data: any): LabelAnnotationsItemType {
        data = typeof data === 'object' ? data : {};
        let result = new LabelAnnotationsItemType();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["mid"] = this.mid !== undefined ? this.mid : <any>null;
        data["description"] = this.description !== undefined ? this.description : <any>null;
        data["score"] = this.score !== undefined ? this.score : <any>null;
        data["topicality"] = this.topicality !== undefined ? this.topicality : <any>null;
        return data;
    }
}

export interface ILabelAnnotationsItemType {
    mid: string;
    description: string;
    score: number;
    topicality: number;
}

export class VisionResponse implements IVisionResponse {
    text?: string | null;
    labels?: LabelAnnotationsItemType[] | null;

    constructor(data?: IVisionResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.text = data["text"] !== undefined ? data["text"] : <any>null;
            if (data["labels"] && data["labels"].constructor === Array) {
                this.labels = [];
                for (let item of data["labels"])
                    this.labels.push(LabelAnnotationsItemType.fromJS(item));
            }
        }
    }

    static fromJS(data: any): VisionResponse {
        data = typeof data === 'object' ? data : {};
        let result = new VisionResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["text"] = this.text !== undefined ? this.text : <any>null;
        if (this.labels && this.labels.constructor === Array) {
            data["labels"] = [];
            for (let item of this.labels)
                data["labels"].push(item.toJSON());
        }
        return data;
    }
}

export interface IVisionResponse {
    text?: string | null;
    labels?: LabelAnnotationsItemType[] | null;
}

export class SwaggerException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if(result !== null && result !== undefined)
        return Observable.throw(result);
    else
        return Observable.throw(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = function() {
                observer.next(this.result);
                observer.complete();
            }
            reader.readAsText(blob);
        }
    });
}
